1
    SWAT Dec 23 2016    VER 2016/Rev 664                                                                 0/ 0/   0      0: 0: 0

    General Input/Output section (file.cio):                                        
    2024/5/11 0:00:00 ARCGIS-SWAT interface AV                                      
                                                                                    


       SUB      GIS  MON   AREAkm2  PRECIPmm SNOMELTmm     PETmm      ETmm      SWmm    PERCmm    SURQmm    GW_Qmm    WYLDmm  SYLDt/ha ORGNkg/ha ORGPkg/haNSURQkg/ha SOLPkg/ha SEDPkg/ha LAT Q(mm)LATNO3kg/hGWNO3kg/haCHOLAmic/LCBODU mg/L DOXQ mg/L TNO3kg/ha   QTILEmm TVAPkg/ha
